#!/usr/bin/env python3
"""Rebuild the catalogue section in the root README from the repo tree."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN_CATALOGUE -->"
END = "<!-- END_CATALOGUE -->"


def status_for(readme: Path) -> str:
    if not readme.exists():
        return "planned"
    text = readme.read_text(encoding="utf-8").lower()
    if "status: planned" in text:
        return "planned"
    if "status: implemented" in text or "implemented now" in text:
        return "implemented"
    tf_files = list(readme.parent.glob("*.tf"))
    has_resource = False
    for tf in tf_files:
        body = tf.read_text(encoding="utf-8")
        if "resource \"" in body or "module \"" in body:
            has_resource = True
            break
    return "implemented" if has_resource else "planned"


def collect(kind: str) -> list[tuple[str, str, str]]:
    base = ROOT / kind
    rows = []
    if not base.exists():
        return rows
    for readme in sorted(base.rglob("README.md")):
        rel = readme.parent.relative_to(ROOT).as_posix()
        name = readme.parent.name
        rows.append((name, rel, status_for(readme)))
    return rows


def table(rows: list[tuple[str, str, str]]) -> str:
    lines = ["| Name | Path | Status |", "|---|---|---|"]
    for name, rel, status in rows:
        lines.append(f"| `{name}` | `{rel}` | {status} |")
    return "\n".join(lines)


def render() -> str:
    parts = [
        "### Shared helpers",
        table(collect("shared")),
        "",
        "### Building blocks",
        table(collect("building-blocks")),
        "",
        "### Patterns",
        table(collect("patterns")),
        "",
        "This table is generated by `python3 scripts/generate_catalogue.py`.",
        "CI fails if you add or remove a module and leave this section stale.",
    ]
    return "\n".join(parts)


def main() -> None:
    generated = render()
    current = README.read_text(encoding="utf-8")
    if BEGIN not in current or END not in current:
        raise SystemExit(f"{README} must contain {BEGIN} and {END} markers")
    before, rest = current.split(BEGIN, 1)
    _, after = rest.split(END, 1)
    updated = f"{before}{BEGIN}\n{generated}\n{END}{after}"
    if updated != current:
        README.write_text(updated, encoding="utf-8")
        print("updated", README)
    else:
        print("catalogue already current")


if __name__ == "__main__":
    main()
